services:
  - type: web
    name: kinosu
    env: node
    region: frankfurt
    plan: free
    buildCommand: npm install && npm run build:full
    startCommand: cd server && npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: RENDER
        value: true
    disk:
      name: uploads
      mountPath: /opt/render/project/src/server/uploads
      sizeGB: 1 